SEED: 42
DEVICE: cuda
MODE: hm
BATCH_SIZE: 16
NUM_WORKERS: 2
NUM_EPOCHS: 200
PRINT_FREQ: 100

DATASET:
  TRAIN: name_of_training_folder
  TEST: name_of_testing_folder
  NUM_KEYPOINTS: 6
  NUM_LIMBS: 5
  MAX_NUM_DETECTIONS: 10
  SIGMA: 2.0
  FLIP: 0.0
  TRANSLATE: 0.4
  SCALE:
    - 0.5
    - 1.5
  ROTATION: 0
  INPUT_SIZE:
    - 384
    - 384
  OUTPUT_SIZE:
    - 192
    - 192
...
